Improve animation support
eventB-Soton/EventB_ProB_Support pull request #7
Opened 2021-07-10 20:33 UTC by cfsnook

fixes some problems with unreliable starting 
improves toolbar and pop-up menus and removes unnecessary dependency on diagrams plugin

2021-07-14 08:21 UTC, tshoang requested changes
I think we should use EPL v2.0 for consistency.

2021-07-14 08:21 UTC, tshoang commented on ac.soton.eventb.probsupport.sdk/feature.properties
> +# Copyright (c) 2020-2021 University of Southampton.
We should use the standard format 2020, 2021 for this

2021-07-14 08:21 UTC, tshoang commented on ac.soton.eventb.probsupport/OSGI-INF/l10n/bundle.properties
> +#  Copyright (c) 2020-2021 University of Southampton.
"2020, 2021"

2021-07-14 08:21 UTC, tshoang commented on ac.soton.eventb.probsupport.feature/feature.properties
>  # are made available under the terms of the Eclipse Public License v1.0
EPL v2.0?

2021-07-14 08:21 UTC, tshoang commented on ac.soton.eventb.probsupport.sdk/feature.properties
>  # are made available under the terms of the Eclipse Public License v1.0
EPL v2.0?

2021-07-14 14:26 UTC, cfsnook commented
Thanks.. i think i have fixed all the copyrights now

2021-07-15 13:29 UTC, cfsnook commented on ac.soton.eventb.probsupport.sdk/feature.properties
>  # are made available under the terms of the Eclipse Public License v1.0
All fixed now

2021-07-15 13:30 UTC, cfsnook commented
Ready to release. I have checked builds locally. Is there some releng to update?

2021-07-15 13:56 UTC, tshoang approved these changes
Looks good to me.

2021-07-15 14:03 UTC, merged